/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControladorProductos;
import model.Productos;
import controller.InventarioXML;
import model.Usuario;
import javax.swing.DefaultListModel;

/**
 *
 * @author Jessica
 */
public class Categoria extends javax.swing.JFrame {

    Usuario usuario;
    Productos producto;
    int ins;
    InventarioXML DatPro = new InventarioXML();
    DefaultListModel lista = new DefaultListModel();
    DefaultListModel modelo = new DefaultListModel();
    String[] categoria = {"Accesorios para vehiculo", "Animales y Mascotas", "Bebes", "Celulares y Telefonos",
        "Coleccionables y Hobbies", "Computacion", "Consolas y Videojuegos",
        "Camaras y Acessorios", "Deportes y Fitness", "Electrodomesticos",
        "Electrica, Audio y Video", "Computacion", "Consolas y Videojuegos",
        "Hogar y Muebles", "Instrumentos Musicales", "Juegos y Juguetes",
        "Libros, Musica y Pelicula", "Relojes,joyas y Visuteria", "Ropa, Zapato y Accesorios",
        "Salud y Belleza", "Otras Categorias"};
    String[] otras = {"Adulto", "Arte y Antiguedades ", "Bebidas y Alimentos", "Esoteria",
        "Eventos y Conciertos", "Cotillones y Recuerdos", "Otros"};
    String[] vehiculo = {"Carros y Camionetas", "Motos", "Nautica", "Otros vehiculos"};
    String[] otrosvehiculo = {"Ambulancia", "Autobuses", "Blindados", "Camiones", "Carros de Coleccion",
        "Carros de competencia", "Carros de golf", "Carros Especiales", "Chocados", "Equipamientos", "Gruas",
        "recreacion", "Tunnig", "Otros"};
    String[] inmueble = {"Accion de club", "Anexos", "Apartamentos", "Casas", "Edificios", "Galpones",
        "Habitaciones", "Haciendas-Fincas", "Hoteles", "Locales", "Negocios", "Oficinas", "Parcelas de Cemento",
        "Resorts", "Terrenos", "Townhouses", "Vacacionales"};

    /**
     * Creates new form Categoria
     */
    public Categoria() {
        initComponents();

    }

    public Categoria(Usuario usu, Productos pro, int instruccion) {
        initComponents();
        ins = instruccion;
        producto = pro;
        usuario = usu;
        LabelCategoria.setText("");
        LabelListo.setVisible(false);
        jPanel2.setVisible(false);
        LabelCat.setVisible(false);
        Otros.setVisible(false);
        casa.setVisible(false);
        carro.setVisible(false);
        if (ins == 3) {
            ControladorProductos.llenaListaCat(lista, categoria, categorialist);
            Otros.setVisible(true);
        } else if (ins == 1) {
            ControladorProductos.llenaListaCat(lista, vehiculo, categorialist);
            carro.setVisible(true);
        } else if (ins == 2) {
            ControladorProductos.llenaListaCat(lista, inmueble, categorialist);
            casa.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        LabelUsuario = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        categorialist = new javax.swing.JList();
        LabelListo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Otros = new javax.swing.JLabel();
        LabelCat = new javax.swing.JLabel();
        LabelCategoria = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listotros = new javax.swing.JList();
        casa = new javax.swing.JLabel();
        carro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(255, 255, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setBackground(new java.awt.Color(255, 255, 255));
        jLabel25.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 102));
        jLabel25.setText("Wonderland");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 40));

        LabelUsuario.setForeground(new java.awt.Color(102, 102, 102));
        LabelUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/perfil.png"))); // NOI18N
        LabelUsuario.setText("Usuario");
        jPanel4.add(LabelUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 30, -1, -1));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        categorialist.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        categorialist.setForeground(new java.awt.Color(0, 51, 153));
        categorialist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                categorialistMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(categorialist);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 110, 208, 280));

        LabelListo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        LabelListo.setForeground(new java.awt.Color(51, 204, 0));
        LabelListo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/agregaricon.png"))); // NOI18N
        LabelListo.setText("Continuar!");
        LabelListo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LabelListoMouseClicked(evt);
            }
        });
        jPanel1.add(LabelListo, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, 212, 210));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Seleccione las Caregorias del producto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("________________________________________________________________________________");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        Otros.setBackground(new java.awt.Color(255, 255, 255));
        Otros.setForeground(new java.awt.Color(0, 0, 153));
        Otros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/pro y otros.png"))); // NOI18N
        Otros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                OtrosMouseClicked(evt);
            }
        });
        Otros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                OtrosKeyReleased(evt);
            }
        });
        jPanel1.add(Otros, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 280));

        LabelCat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelCat.setForeground(new java.awt.Color(102, 102, 102));
        LabelCat.setText("Categoria escogida:");
        jPanel1.add(LabelCat, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 110, -1, 27));

        LabelCategoria.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LabelCategoria.setForeground(new java.awt.Color(153, 0, 0));
        LabelCategoria.setText("Categoria");
        jPanel1.add(LabelCategoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, 31));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setForeground(new java.awt.Color(204, 204, 204));

        listotros.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        listotros.setForeground(new java.awt.Color(0, 51, 153));
        listotros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listotrosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listotros);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 30, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 110, 220, 310));

        casa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/inmuebles.png"))); // NOI18N
        casa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                casaMouseClicked(evt);
            }
        });
        jPanel1.add(casa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, 280));

        carro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesSistema/vehiculos.png"))); // NOI18N
        carro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                carroMouseClicked(evt);
            }
        });
        jPanel1.add(carro, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, 280));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, 995, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void OtrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_OtrosMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_OtrosMouseClicked

    private void OtrosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_OtrosKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_OtrosKeyReleased

    private void LabelListoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LabelListoMouseClicked
        // TODO add your handling code here:
        AgregaProductos2 control2 = new AgregaProductos2(usuario, producto);
        control2.setLocationRelativeTo(null);
        control2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_LabelListoMouseClicked

    private void categorialistMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_categorialistMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int posicion = categorialist.getSelectedIndex();
            String categoria = String.valueOf(lista.getElementAt(posicion));
            if (ins == 3) {
                if (categoria != "Otras Categorias") {
                    producto.setCategoria(categoria);
                    DatPro.actualizarProducto(producto);
                    LabelCategoria.setText(categoria);
                    LabelCat.setVisible(true);
                    LabelListo.setVisible(true);
                } else {
                    modelo.clear();
                    ControladorProductos.llenaListaCat(modelo, otras, listotros);
                    jPanel2.setVisible(true);
                }
            } else if (ins == 1) {
                if (categoria != "Otros vehiculos") {
                    producto.setCategoria(categoria);
                    DatPro.actualizarProducto(producto);
                    LabelCategoria.setText(categoria);
                    LabelCat.setVisible(true);
                    LabelListo.setVisible(true);
                } else {
                    modelo.clear();
                    ControladorProductos.llenaListaCat(modelo, otrosvehiculo, listotros);
                    jPanel2.setVisible(true);
                }
            } else {
                producto.setCategoria(categoria);
                DatPro.actualizarProducto(producto);
                LabelCategoria.setText(categoria);
                LabelCat.setVisible(true);
                LabelListo.setVisible(true);
            }
        }
    }//GEN-LAST:event_categorialistMouseClicked

    private void listotrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listotrosMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            int posicion = listotros.getSelectedIndex();
            String categoria = String.valueOf(modelo.getElementAt(posicion));
            producto.setCategoria(categoria);
            LabelCat.setVisible(true);
            LabelListo.setVisible(true);
            DatPro.actualizarProducto(producto);
            LabelCategoria.setText(categoria);
        }
    }//GEN-LAST:event_listotrosMouseClicked

    private void casaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_casaMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_casaMouseClicked

    private void carroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_carroMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_carroMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Categoria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Categoria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Categoria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Categoria.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Categoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelCat;
    private javax.swing.JLabel LabelCategoria;
    private javax.swing.JLabel LabelListo;
    private javax.swing.JLabel LabelUsuario;
    private javax.swing.JLabel Otros;
    private javax.swing.JLabel carro;
    private javax.swing.JLabel casa;
    private javax.swing.JList categorialist;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList listotros;
    // End of variables declaration//GEN-END:variables
}
